<?xml version="1.0" encoding="utf-8"?><Database Name="SoiSo" Class="CS3MDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=SoiSo;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SoiSoConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.CS_DangKyTaiKhoan" Method="CS_DangKyTaiKhoan">
    <Parameter Name="Nickname" Parameter="nickname" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Number" Parameter="number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="CS_DangKyTaiKhoanResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_DangNhap" Method="CS_DangNhap">
    <Parameter Name="Nickname" Parameter="nickname" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CS_DangNhapResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_GetKQXS" Method="CS_GetKQXS">
    <Parameter Name="Area" Parameter="area" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NgayXo" Parameter="ngayXo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="CS_GetKQXSResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayXo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenGiai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="So" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VitriDoXanh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VitriXanh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_AdminGetKQXS" Method="CS_AdminGetKQXS">
    <ElementType Name="CS_AdminGetKQXSResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayXo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserCreated" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KhuVuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Added" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_AdminGetChiTietKQXS" Method="CS_AdminGetChiTietKQXS">
    <Parameter Name="IdKQXS" Parameter="idKQXS" Type="System.Int32" DbType="Int" />
    <ElementType Name="CS_AdminGetChiTietKQXSResult">
      <Column Name="IdKQXS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="So" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TenGiai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VitriDoXanh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_AdminInsertKQXS" Method="CS_AdminInsertKQXS">
    <Parameter Name="IdArea" Parameter="idArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="NgayXo" Parameter="ngayXo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateCreate" Parameter="dateCreate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserCreate" Parameter="userCreate" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="CS_AdminInsertKQXSResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_AdminGetAllArea" Method="CS_AdminGetAllArea">
    <ElementType Name="CS_AdminGetAllAreaResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_AdminInsertChiTietKQXS" Method="CS_AdminInsertChiTietKQXS">
    <Parameter Name="IdKQXS" Parameter="idKQXS" Type="System.Int32" DbType="Int" />
    <Parameter Name="TenGiai" Parameter="tenGiai" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="So" Parameter="so" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ViTriDoXanh" Parameter="viTriDoXanh" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="CS_AdminInsertChiTietKQXSResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_GetDauDuoi" Method="CS_GetDauDuoi">
    <Parameter Name="Area" Parameter="area" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NgayXo" Parameter="ngayXo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="CS_GetDauDuoiResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdKQXS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dau0" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau1" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau2" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau3" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau4" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau5" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau6" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau7" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau8" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Dau9" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi0" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi1" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi2" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi3" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi4" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi5" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi6" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi7" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi8" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="Duoi9" Type="System.String" DbType="VarChar(350)" CanBeNull="true" />
      <Column Name="LoDo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_GetSoXuatHien" Method="CS_GetSoXuatHien">
    <Parameter Name="Area" Parameter="area" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NgayXo" Parameter="ngayXo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="CS_GetSoXuatHienResult">
      <Column Name="SoXuatHien" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoLan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>