#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoiSo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoiSo")]
	public partial class CS3MDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CS3MDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SoiSoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CS_DangKyTaiKhoan")]
		public ISingleResult<CS_DangKyTaiKhoanResult> CS_DangKyTaiKhoan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nickname", DbType="VarChar(20)")] string nickname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="VarChar(20)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nickname, number, password, email);
			return ((ISingleResult<CS_DangKyTaiKhoanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CS_DangNhap")]
		public ISingleResult<CS_DangNhapResult> CS_DangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nickname", DbType="VarChar(20)")] string nickname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nickname, password);
			return ((ISingleResult<CS_DangNhapResult>)(result.ReturnValue));
		}
	}
	
	public partial class CS_DangKyTaiKhoanResult
	{
		
		private int _Result;
		
		public CS_DangKyTaiKhoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class CS_DangNhapResult
	{
		
		private int _Result;
		
		public CS_DangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
