<?xml version="1.0" encoding="utf-8"?><Database Name="SoiSo" Class="CS3MDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=SoiSo;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SoiSoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.CS_DangKyTaiKhoan" Method="CS_DangKyTaiKhoan">
    <Parameter Name="Nickname" Parameter="nickname" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Number" Parameter="number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="CS_DangKyTaiKhoanResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_DangNhap" Method="CS_DangNhap">
    <Parameter Name="Nickname" Parameter="nickname" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CS_DangNhapResult">
      <Column Name="Result" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CS_GetKQXS" Method="CS_GetKQXS">
    <Parameter Name="Area" Parameter="area" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NgayXo" Parameter="ngayXo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="CS_GetKQXSResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayXo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenGiai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="So" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VitriDoXanh" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>