#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSoiSo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SoiSo")]
	public partial class CS3MDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCS_Area(CS_Area instance);
    partial void UpdateCS_Area(CS_Area instance);
    partial void DeleteCS_Area(CS_Area instance);
    partial void InsertCS_KQX(CS_KQX instance);
    partial void UpdateCS_KQX(CS_KQX instance);
    partial void DeleteCS_KQX(CS_KQX instance);
    partial void InsertCS_KQXS_ChiTiet(CS_KQXS_ChiTiet instance);
    partial void UpdateCS_KQXS_ChiTiet(CS_KQXS_ChiTiet instance);
    partial void DeleteCS_KQXS_ChiTiet(CS_KQXS_ChiTiet instance);
    #endregion
		
		public CS3MDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SoiSoConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CS3MDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CS_Area> CS_Areas
		{
			get
			{
				return this.GetTable<CS_Area>();
			}
		}
		
		public System.Data.Linq.Table<CS_KQX> CS_KQXes
		{
			get
			{
				return this.GetTable<CS_KQX>();
			}
		}
		
		public System.Data.Linq.Table<CS_KQXS_ChiTiet> CS_KQXS_ChiTiets
		{
			get
			{
				return this.GetTable<CS_KQXS_ChiTiet>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CS_DangKyTaiKhoan")]
		public ISingleResult<CS_DangKyTaiKhoanResult> CS_DangKyTaiKhoan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nickname", DbType="VarChar(20)")] string nickname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="VarChar(20)")] string number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nickname, number, password, email);
			return ((ISingleResult<CS_DangKyTaiKhoanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CS_DangNhap")]
		public ISingleResult<CS_DangNhapResult> CS_DangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nickname", DbType="VarChar(20)")] string nickname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nickname, password);
			return ((ISingleResult<CS_DangNhapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CS_GetKQXS")]
		public ISingleResult<CS_GetKQXSResult> CS_GetKQXS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Area", DbType="VarChar(20)")] string area, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayXo", DbType="DateTime")] System.Nullable<System.DateTime> ngayXo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), area, ngayXo);
			return ((ISingleResult<CS_GetKQXSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CS_GetChiTietKQXS")]
		public ISingleResult<CS_GetChiTietKQXSResult> CS_GetChiTietKQXS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdKQXS", DbType="Int")] System.Nullable<int> idKQXS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKQXS);
			return ((ISingleResult<CS_GetChiTietKQXSResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_Area")]
	public partial class CS_Area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Area;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    #endregion
		
		public CS_Area()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="NVarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KQXS")]
	public partial class CS_KQX : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdArea;
		
		private System.Nullable<System.DateTime> _NgayXo;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _UserCreated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdAreaChanging(System.Nullable<int> value);
    partial void OnIdAreaChanged();
    partial void OnNgayXoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXoChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnUserCreatedChanging(string value);
    partial void OnUserCreatedChanged();
    #endregion
		
		public CS_KQX()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArea", DbType="Int")]
		public System.Nullable<int> IdArea
		{
			get
			{
				return this._IdArea;
			}
			set
			{
				if ((this._IdArea != value))
				{
					this.OnIdAreaChanging(value);
					this.SendPropertyChanging();
					this._IdArea = value;
					this.SendPropertyChanged("IdArea");
					this.OnIdAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXo", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXo
		{
			get
			{
				return this._NgayXo;
			}
			set
			{
				if ((this._NgayXo != value))
				{
					this.OnNgayXoChanging(value);
					this.SendPropertyChanging();
					this._NgayXo = value;
					this.SendPropertyChanged("NgayXo");
					this.OnNgayXoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreated", DbType="NVarChar(50)")]
		public string UserCreated
		{
			get
			{
				return this._UserCreated;
			}
			set
			{
				if ((this._UserCreated != value))
				{
					this.OnUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._UserCreated = value;
					this.SendPropertyChanged("UserCreated");
					this.OnUserCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS_KQXS_ChiTiet")]
	public partial class CS_KQXS_ChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdKQXS;
		
		private string _TenGiai;
		
		private string _So;
		
		private string _VitriDoXanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdKQXSChanging(System.Nullable<int> value);
    partial void OnIdKQXSChanged();
    partial void OnTenGiaiChanging(string value);
    partial void OnTenGiaiChanged();
    partial void OnSoChanging(string value);
    partial void OnSoChanged();
    partial void OnVitriDoXanhChanging(string value);
    partial void OnVitriDoXanhChanged();
    #endregion
		
		public CS_KQXS_ChiTiet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKQXS", DbType="Int")]
		public System.Nullable<int> IdKQXS
		{
			get
			{
				return this._IdKQXS;
			}
			set
			{
				if ((this._IdKQXS != value))
				{
					this.OnIdKQXSChanging(value);
					this.SendPropertyChanging();
					this._IdKQXS = value;
					this.SendPropertyChanged("IdKQXS");
					this.OnIdKQXSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiai", DbType="VarChar(10)")]
		public string TenGiai
		{
			get
			{
				return this._TenGiai;
			}
			set
			{
				if ((this._TenGiai != value))
				{
					this.OnTenGiaiChanging(value);
					this.SendPropertyChanging();
					this._TenGiai = value;
					this.SendPropertyChanged("TenGiai");
					this.OnTenGiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So", DbType="VarChar(10)")]
		public string So
		{
			get
			{
				return this._So;
			}
			set
			{
				if ((this._So != value))
				{
					this.OnSoChanging(value);
					this.SendPropertyChanging();
					this._So = value;
					this.SendPropertyChanged("So");
					this.OnSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VitriDoXanh", DbType="VarChar(10)")]
		public string VitriDoXanh
		{
			get
			{
				return this._VitriDoXanh;
			}
			set
			{
				if ((this._VitriDoXanh != value))
				{
					this.OnVitriDoXanhChanging(value);
					this.SendPropertyChanging();
					this._VitriDoXanh = value;
					this.SendPropertyChanged("VitriDoXanh");
					this.OnVitriDoXanhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class CS_DangKyTaiKhoanResult
	{
		
		private int _Result;
		
		public CS_DangKyTaiKhoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class CS_DangNhapResult
	{
		
		private int _Result;
		
		public CS_DangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int NOT NULL")]
		public int Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class CS_GetKQXSResult
	{
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _NgayXo;
		
		private string _TenGiai;
		
		private string _So;
		
		public CS_GetKQXSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXo", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXo
		{
			get
			{
				return this._NgayXo;
			}
			set
			{
				if ((this._NgayXo != value))
				{
					this._NgayXo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiai", DbType="VarChar(10)")]
		public string TenGiai
		{
			get
			{
				return this._TenGiai;
			}
			set
			{
				if ((this._TenGiai != value))
				{
					this._TenGiai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So", DbType="VarChar(10)")]
		public string So
		{
			get
			{
				return this._So;
			}
			set
			{
				if ((this._So != value))
				{
					this._So = value;
				}
			}
		}
	}
	
	public partial class CS_GetChiTietKQXSResult
	{
		
		private System.Nullable<int> _IdKQXS;
		
		private string _So;
		
		private string _TenGiai;
		
		private string _VitriDoXanh;
		
		public CS_GetChiTietKQXSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKQXS", DbType="Int")]
		public System.Nullable<int> IdKQXS
		{
			get
			{
				return this._IdKQXS;
			}
			set
			{
				if ((this._IdKQXS != value))
				{
					this._IdKQXS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So", DbType="VarChar(10)")]
		public string So
		{
			get
			{
				return this._So;
			}
			set
			{
				if ((this._So != value))
				{
					this._So = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiai", DbType="VarChar(10)")]
		public string TenGiai
		{
			get
			{
				return this._TenGiai;
			}
			set
			{
				if ((this._TenGiai != value))
				{
					this._TenGiai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VitriDoXanh", DbType="VarChar(10)")]
		public string VitriDoXanh
		{
			get
			{
				return this._VitriDoXanh;
			}
			set
			{
				if ((this._VitriDoXanh != value))
				{
					this._VitriDoXanh = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
